version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123!
    ports:
      - "1433:1433"
    networks:
      - zurich-network
#    healthcheck:
#      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P Your_password123! -Q 'SELECT 1'"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  api:
    build:
      context: .
      dockerfile: api.zurich.rarp/Dockerfile
    container_name: zurich-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver2,1433;Database=ZurichRarp;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;
    ports:
      - "5000:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - zurich-network

networks:
  zurich-network:
    driver: bridge
