// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using biz.zurich.rarp.Entities;

namespace dal.zurich.rarp.DBContext;

public partial class ZurichRarpContext : DbContext
{
    public ZurichRarpContext(DbContextOptions<ZurichRarpContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Poliza> Polizas { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Poliza>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Polizas__3214EC07F08D18A0");

            entity.HasIndex(e => e.Estado, "IX_Polizas_Estado");

            entity.HasIndex(e => new { e.FechaInicio, e.FechaExpiracion }, "IX_Polizas_Fechas");

            entity.HasIndex(e => e.TipoPoliza, "IX_Polizas_TipoPoliza");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.MontoAsegurado).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TipoPoliza)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Cliente).WithMany(p => p.Polizas)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Polizas__Cliente__412EB0B6");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC0763DD4FD3");

            entity.HasIndex(e => e.Nombre, "UQ__Roles__75E3EFCFF7F69AE1").IsUnique();

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Clientes__3214EC07FF6EE26C");

            entity.HasIndex(e => e.CorreoElectronico, "IX_Clientes_CorreoElectronico");

            entity.HasIndex(e => e.NombreCompleto, "IX_Clientes_NombreCompleto");

            entity.HasIndex(e => e.NumeroIdentificacion, "IX_Clientes_NumeroIdentificacion");

            entity.HasIndex(e => e.NumeroIdentificacion, "UQ__Clientes__FCA68D91A9E664D0").IsUnique();

            entity.Property(e => e.Contrasena)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("contrasena");
            entity.Property(e => e.CorreoElectronico)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Direccion).HasMaxLength(200);
            entity.Property(e => e.NombreCompleto)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.NumeroIdentificacion)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Telefono)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Rol).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.RolId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Clientes__RolId__3D5E1FD2");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}