// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.zurich.rarp.Entities;

public partial class Poliza
{
    public int Id { get; set; }

    public int ClienteId { get; set; }

    public string TipoPoliza { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly FechaExpiracion { get; set; }

    public decimal MontoAsegurado { get; set; }

    public string Estado { get; set; }

    public virtual Usuario Cliente { get; set; }
}