// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.zurich.rarp.Entities;

public partial class Usuario
{
    public int Id { get; set; }

    public string NumeroIdentificacion { get; set; }

    public string NombreCompleto { get; set; }

    public string CorreoElectronico { get; set; }

    public string Telefono { get; set; }

    public string Direccion { get; set; }

    public int RolId { get; set; }

    public string Contrasena { get; set; }

    public virtual ICollection<Poliza> Polizas { get; set; } = new List<Poliza>();

    public virtual Role Rol { get; set; }
}